### ISSUE TITLE
test with flag

### ISSUE THREAD

**Issue by StephanKrauss** [mindplay-dk/testies#6]
Hello, 

i start a new project.
For this project i'm looking for a simple unit test.
In my project i will control the value of a data transfer object.

For example: 
$result1 = $myDTOobject->getResult1();

Now i will test my $result1 an array;

 test(
        'Describe your test here',
        function () {
            ok(is_array($result1), 'it works!');
        }
  );

run();

Is there a better way for checking the $result1 ?
I need a return of the assertation as flag.

For example:

check() is true or false.

Can you help ?

Your sincerly 

Stephan

**Comment by mindplay-dk** [comment]
> Is there a better way for checking the $result1 ?

What do you mean by "better"?

> I need a return of the assertation as flag.

I don't know what you mean.

Do you need the value of the assertion?

You could use an intermediary variable for that:

```
$is_array = is_array($result1);

ok($is_array, 'it works!');

if ($is_array) {
  // ...
}
```

(Conditional tests aren't really a good idea though, if that's what you're planning.)

**Comment by StephanKrauss** [comment]
Hello,

thanks for the quick replay.
In my project there is a data-transfer-object.
This DTO has insert same arrays.
I will test, exist a array from this DTO and how many rows.
When the test finished i get an information. 
All is o.k. a $flag == true
or an error is $flag == false

It is not a classical unit test.
It is the control of the values from a DTO.


Your sincerly

Stephan

**Comment by mindplay-dk** [comment]
I've written lots of DTO integration tests with this framework.

For example, here's a test that saves a `Profile` DTO, loads it, and compares it with the original:

```php
test(
    'can load and save Profiles',
    function () {
        create_container()->call(function (ProfileRepository $repo, ProfileFaker $faker) {
            $profile = $faker->createFakeProfile();

            $repo->saveProfile($profile);

            ok($profile->id > 0, "Profile ID assigned");

            $loaded = $repo->loadProfile($profile->id);

            foreach (get_object_vars($profile) as $name => $value) {
                eq($loaded->$name, $value, "can load Profile::\${$name}");
            }
        });
    }
);
```

(The `create_container()` call creates the IOC container I used in this project, and the `call` method provides the two services I need from the container for this test.)

Again, I'm not really sure what you're looking for.

There's only one type of test in this framework - whether those are classical unit tests, integration tests, or functional tests (using some client library) is up to you.

The tests are just simple assertions about the state of whatever it is you're testing - along the lines of Go's test-framework, tests really are "just code", so you should be able to do whatever it is you want to do. Only the framework won't do it *for* you. Unlike "large" test-frameworks, you won't find a bunch of assertion helpers to test specific things - the philosophy is for you to just do what you'd be doing any other day while writing your project code: just write regular PHP.

You can write custom assertions, but you probably shouldn't use it to write very general assertions like most other test-frameworks have - this feature is intended to help you reuse repetitive, *project-specific* testing tasks.

This is covered in the README, along with the overall concept and philosophy.

Not sure what else you're looking for, sorry. 🙂
